export const hubData = [
  {
    postId: 1,
    userId: 1,
    boardType: "HUB",
    title: "Amateurs - 데브코스 최종 프로젝트",
    content:
      "<h1>Amateurs 프로젝트입니다.</h1><p>수강생들의 자유로운 소통과 네트워킹을 위한 커뮤니티 플랫폼입니다. 다양한 주제의 게시판을 통해 지식을 공유하고, 스터디 및 프로젝트 팀원을 모집하며 함께 성장할 수 있습니다.</p><p><b>주요 기능:</b></p><ul><li>통합 게시판: 자유, 질문, 스터디 등 다양한 주제</li><li>프로젝트 허브: 팀 프로젝트 쇼케이스 및 멤버 모집</li><li>실시간 채팅: 사용자 간 1:1 및 그룹 채팅</li><li>알림 기능: 새 글, 댓글, 채팅 등 실시간 알림</li></ul><p>이 프로젝트를 통해 저희 팀은 실제 서비스 개발의 A to Z를 경험할 수 있었습니다. 기획부터 디자인, 개발, 배포까지 전 과정을 함께하며 협업 능력과 기술적 깊이를 더할 수 있는 소중한 시간이었습니다.</p>",
    viewCount: 1582,
    likeCount: 25,
    isDeleted: false,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T11:30:00Z",
    tags: ["Java", "SpringBoot", "React", "WebSocket"],
    postImages: [
      {
        id: 1,
        postId: 1,
        imageUrl: "https://picsum.photos/seed/amateurs1/800/600",
      },
      {
        id: 2,
        postId: 1,
        imageUrl: "https://picsum.photos/seed/amateurs2/800/600",
      },
      {
        id: 3,
        postId: 1,
        imageUrl: "https://picsum.photos/seed/amateurs3/800/600",
      },
    ],
    nickname: "김팀장",
    profileImageUrl: "https://picsum.photos/id/11/40/40",
    devcourseName: "프론트엔드",
    devcourseBatch: 3,
    isBookmarked: false,
    isLiked: false,
    bookmarkCount: 0,
    commentCount: 2,
    comments: [
      {
        id: 1,
        postId: 1,
        nickname: "박동료",
        profileImageUrl: "https://picsum.photos/id/51/40/40",
        devcourseName: "프론트엔드",
        parentCommentId: null,
        content: "와, 정말 멋진 프로젝트네요! 고생 많으셨습니다.",
        replyCount: 0,
        likeCount: 0,
        hasLiked: false,
        createdAt: "2025-07-20T12:00:00Z",
        updatedAt: "2025-07-20T12:00:00Z",
      },
      {
        id: 2,
        postId: 1,
        nickname: "최멘토",
        profileImageUrl: "https://picsum.photos/id/61/40/40",
        devcourseName: "AI 엔지니어링",
        parentCommentId: null,
        content: "최종 발표 때 인상 깊게 봤습니다. 앞으로가 더 기대됩니다!",
        replyCount: 0,
        likeCount: 0,
        hasLiked: false,
        createdAt: "2025-07-21T09:30:00Z",
        updatedAt: "2025-07-21T09:30:00Z",
      },
    ],
    project: {
      postId: 1,
      startedAt: "2025-06-13",
      endedAt: "2025-07-13",
      simpleContent:
        "우리 프로젝트를 한 줄로 소개할 수 있어요. 그 대신 진짜 진짜 멋있어야 해요.",
      devcourseTrack: "프론트엔드",
      devcourseBatch: 3,
      githubUrl:
        "https://github.com/prgrms-aibe-devcourse/AIBE1-FinalProject-Team01-FE",
      demoUrl: "https://amateurs.com",
      projectMembers: [
        { name: "김팀장", role: "CEO & PM & 응원" },
        { name: "이개발", role: "프론트엔드 개발자" },
        { name: "박서버", role: "백엔드 개발자" },
        { name: "최디비", role: "데이터베이스 설계" },
      ],
    },
  },
  {
    postId: 2,
    userId: 2,
    boardType: "HUB",
    title: "AI 챗봇 서비스 '코코'",
    content:
      "<h1>AI 챗봇 서비스 '코코'입니다.</h1><p>자연어 처리 기술을 활용하여 사용자와 대화하는 AI 챗봇 서비스입니다. 감성 분석 기능을 통해 사용자의 기분을 파악하고 맞춤형 응답을 제공합니다.</p>",
    viewCount: 980,
    likeCount: 18,
    isDeleted: false,
    createdAt: "2025-07-18T14:00:00Z",
    updatedAt: "2025-07-18T15:00:00Z",
    tags: ["Python", "TensorFlow", "Flask", "NLP"],
    postImages: [
      { id: 4, postId: 2, imageUrl: "https://picsum.photos/seed/coco/800/600" },
    ],
    nickname: "AI마스터",
    profileImageUrl: "https://picsum.photos/id/22/40/40",
    devcourseName: "생성형 AI 백엔드",
    devcourseBatch: 1,
    isBookmarked: true,
    isLiked: false,
    bookmarkCount: 0,
    commentCount: 0,
    comments: [],
    project: {
      postId: 2,
      startedAt: "2025-03-01",
      endedAt: "2025-05-30",
      simpleContent: "당신의 마음을 이해하는 AI 친구, 코코",
      devcourseTrack: "생성형 AI 백엔드",
      devcourseBatch: 1,
      githubUrl: "https://github.com/coco-project",
      demoUrl: "https://coco-chatbot.com",
      projectMembers: [
        { name: "AI마스터", role: "AI 모델 개발" },
        { name: "서버왕", role: "백엔드 API 개발" },
      ],
    },
  },
  {
    postId: 3,
    userId: 3,
    boardType: "HUB",
    title: "클라우드 기반 데이터 파이프라인 구축",
    content:
      "<h1>클라우드 기반 데이터 파이프라인 구축입니다.</h1><p>AWS 서비스를 활용하여 대용량 데이터를 수집, 처리, 분석하는 파이프라인을 구축했습니다. 데이터 시각화 대시보드를 통해 인사이트를 제공합니다.</p>",
    viewCount: 2100,
    likeCount: 42,
    isDeleted: false,
    createdAt: "2025-07-15T09:00:00Z",
    updatedAt: "2025-07-15T10:00:00Z",
    tags: ["AWS", "Kafka", "Spark", "DataPipeline"],
    postImages: [
      {
        id: 5,
        postId: 3,
        imageUrl: "https://picsum.photos/seed/datapipe1/800/600",
      },
      {
        id: 6,
        postId: 3,
        imageUrl: "https://picsum.photos/seed/datapipe2/800/600",
      },
    ],
    nickname: "데이터장인",
    profileImageUrl: "https://picsum.photos/id/33/40/40",
    devcourseName: "클라우드 백엔드",
    devcourseBatch: 2,
    isBookmarked: false,
    isLiked: false,
    bookmarkCount: 0,
    commentCount: 0,
    comments: [],
    project: {
      postId: 3,
      startedAt: "2025-04-10",
      endedAt: "2025-06-10",
      simpleContent: "빅데이터를 가치로 바꾸는 클라우드 파이프라인",
      devcourseTrack: "클라우드 백엔드",
      devcourseBatch: 2,
      githubUrl: "https://github.com/data-pipeline-project",
      demoUrl: null,
      projectMembers: [
        { name: "데이터장인", role: "데이터 엔지니어" },
        { name: "클라우드고수", role: "인프라 설계" },
        { name: "시각화맨", role: "프론트엔드 개발" },
      ],
    },
  },
];
