/**
 * DM 관련 더미 데이터
 */

export const dummyChatData = [
  {
    id: "1",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "5분 전",
    isRead: false,
  },
  {
    id: "2",
    nickname: "홍식이",
    profileImage: null,
    lastMessage: "오늘이 뭐 먹었어 어리지니까?",
    timestamp: "1시간 전",
    isRead: true,
  },
  {
    id: "3",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "2시간 전",
    isRead: true,
  },
  {
    id: "4",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "3시간 전",
    isRead: true,
  },
  {
    id: "5",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "4시간 전",
    isRead: true,
  },
  {
    id: "6",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "5시간 전",
    isRead: true,
  },
  {
    id: "7",
    nickname: "으석이",
    profileImage: null,
    lastMessage: "무이지 잘 지내...",
    timestamp: "6시간 전",
    isRead: true,
  },
];

export const dummyMessages = [
  {
    id: "msg1",
    chatId: "1",
    senderId: "user1",
    senderName: "으석이",
    text: "안녕하세요 DM을 이용해 어려지니까? 차근 모르고 있는 것 같아서 질문이 있어요",
    timestamp: "오후 2:30",
    isMe: false,
  },
  {
    id: "msg2",
    chatId: "1",
    senderId: "current-user",
    senderName: "김무이지",
    text: "오석이 잘 지내셔...",
    timestamp: "오후 2:31",
    isMe: true,
  },
  {
    id: "msg3",
    chatId: "1",
    senderId: "user1",
    senderName: "으석이",
    text: "내일이 감자어쳐 어리지니까?",
    timestamp: "오후 2:32",
    isMe: false,
  },
  {
    id: "msg4",
    chatId: "1",
    senderId: "current-user",
    senderName: "김무이지",
    text: "내일이 감자어쳐 어리지니까?",
    timestamp: "오후 2:33",
    isMe: true,
  },
  {
    id: "msg5",
    chatId: "2",
    senderId: "user2",
    senderName: "홍식이",
    text: "오늘이 뭐 먹었어 어리지니까?",
    timestamp: "오후 1:15",
    isMe: false,
  },
  {
    id: "msg6",
    chatId: "2",
    senderId: "current-user",
    senderName: "김무이지",
    text: "저는 김치찌개 먹었어요!",
    timestamp: "오후 1:16",
    isMe: true,
  },
];
