export const posts = [
  {
    postId: 1,
    userId: 1,
    boardType: "FREE",
    title: "요즘 아침에 수업듣기 너무 빡세네요",
    content:
      '아침에 일어나기 너무 힘들어요... 다들 어떻게 극복하시나요?<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZLlkP9EXGiropFvkyGVSJiQDkC3o8huVh06NIu0s4LHyTy_sTToM9vn2xKF5HwqFDF4A&usqp=CAU" alt="Tired student"></p><p>특히 9시 수업이 가장 힘든데, 여러분들은 어떤 방법으로 아침 기상을 하시나요? </p> <p> <img src="https://t4.ftcdn.net/jpg/02/66/72/41/360_F_266724133_uJj0HlXvsmFltJo5YDOVSG6p4Y8sQiZB.jpg">  </p> <p> 알람을 여러 개 맞춰놔도 계속 꺼버리게 되네요. 좋은 팁이 있다면 공유 부탁드립니다!</p>',
    tags: ["피곤함", "데브코스", "아침수업"],
    likeCount: 24,
    viewCount: 157,
    commentCount: 2,
    isDeleted: false,
    postImages: [
      {
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZLlkP9EXGiropFvkyGVSJiQDkC3o8huVh06NIu0s4LHyTy_sTToM9vn2xKF5HwqFDF4A&usqp=CAU",
      },
    ],
    isBookmarked: false,
    isLiked: false,
    createdAt: "2024-12-19T14:30:00Z",
    updatedAt: "2024-12-19T14:30:00Z",
    nickname: "김루이지",
    profileImageUrl: "https://via.placeholder.com/40",
    devcourseName: "프론트엔드",
    comments: [
      {
        id: 1,
        userId: 4,
        postId: 1,
        parentCommentId: null,
        content:
          "저도 똑같은 고민이에요! 알람 15개씩 맞춰놔도 다 꺼버리게 되더라고요 ㅠㅠ",
        likeCount: 3,
        isDeleted: false,
        createdAt: "2024-12-19T15:00:00Z",
        updatedAt: "2024-12-19T15:00:00Z",
        nickname: "이민수",
        profileImageUrl: "https://via.placeholder.com/40",
        devcourseName: "프론트엔드",
        replies: [],
      },
      {
        id: 2,
        userId: 5,
        postId: 1,
        parentCommentId: null,
        content:
          "알람 앱을 바꿔보세요! 수학 문제 풀어야 꺼지는 앱 써보니까 효과 있더라고요",
        likeCount: 8,
        isDeleted: false,
        createdAt: "2024-12-19T15:30:00Z",
        updatedAt: "2024-12-19T15:30:00Z",
        nickname: "박수진",
        profileImageUrl: "https://via.placeholder.com/40",
        devcourseName: "데이터분석",
        replies: [
          {
            id: 3,
            userId: 1,
            postId: 1,
            parentCommentId: 2,
            content: "오 좋은 아이디어네요! 앱 이름 알려주실 수 있을까요?",
            likeCount: 1,
            isDeleted: false,
            createdAt: "2024-12-19T16:00:00Z",
            updatedAt: "2024-12-19T16:00:00Z",
            nickname: "김루이지",
            profileImageUrl: "https://via.placeholder.com/40",
            devcourseName: "프론트엔드",
            replies: [],
          },
        ],
      },
    ],
  },
  {
    postId: 2,
    userId: 2,
    boardType: "QNA",
    title: "React Hook Form vs Formik 비교 분석해봤어요",
    content:
      "<p>둘 다 써보니 장단점이 확실히 있네요. 여러분은 어떤 걸 선호하시나요?</p><p>프로젝트를 진행하면서 두 라이브러리를 모두 사용해봤는데, 각각의 장단점이 뚜렷하더라고요.</p> <p>React Hook Form: 성능이 좋고 리렌더링이 적음</p> <p>Formik: 문서화가 잘 되어있고 커뮤니티가 활발함</p> <p>Hook Form: TypeScript 지원이 더 우수함</p> <p>Formik: 복잡한 폼 validation에 유리함</p>",
    tags: ["React", "Hook", "비교", "분석"],
    likeCount: 10,
    viewCount: 1457,
    commentCount: 1,
    isDeleted: false,
    postImages: [],
    isBookmarked: false,
    isLiked: false,
    createdAt: "2024-12-19T06:30:00Z",
    updatedAt: "2024-12-19T06:30:00Z",
    nickname: "홍길동",
    profileImageUrl: "https://via.placeholder.com/40",
    devcourseName: "백엔드",
    comments: [
      {
        id: 4,
        userId: 6,
        postId: 2,
        parentCommentId: null,
        content: "저는 Hook Form 파입니다. 성능 차이가 확실히 느껴져요!",
        likeCount: 5,
        isDeleted: false,
        createdAt: "2024-12-19T07:00:00Z",
        updatedAt: "2024-12-19T07:00:00Z",
        nickname: "최개발",
        profileImageUrl: "https://via.placeholder.com/40",
        devcourseName: "프론트엔드",
        replies: [],
      },
    ],
  },
  {
    postId: 3,
    userId: 3,
    boardType: "RETROSPECT",
    title: "첫 프로젝트 회고: 실패와 성공의 경험담",
    content:
      "<p>리액트 어렵네요... 하지만 포기하지 않고 끝까지 해냈습니다.</p><p>처음에는 정말 막막했는데, 하나씩 배워가면서 조금씩 이해가 되기 시작했어요. 특히 컴포넌트 구조를 잡는 게 가장 어려웠던 것 같습니다.</p>",
    tags: ["회고", "프로젝트", "성장"],
    likeCount: 32,
    viewCount: 892,
    commentCount: 1,
    isDeleted: false,
    postImages: [],
    isBookmarked: false,
    isLiked: false,
    createdAt: "2024-12-18T15:20:00Z",
    updatedAt: "2024-12-18T15:20:00Z",
    nickname: "박개발",
    profileImageUrl: "https://via.placeholder.com/40",
    devcourseName: "생성형 AI 백엔드",
    comments: [
      {
        id: 5,
        userId: 7,
        postId: 3,
        parentCommentId: null,
        content:
          "포기하지 않고 끝까지 하신 게 정말 대단해요! 계속 화이팅하세요 💪",
        likeCount: 12,
        isDeleted: false,
        createdAt: "2024-12-18T16:00:00Z",
        updatedAt: "2024-12-18T16:00:00Z",
        nickname: "김멘토",
        profileImageUrl: "https://via.placeholder.com/40",
        devcourseName: "AI 엔지니어링",
        replies: [],
      },
    ],
  },
];
