// 팀원구하기(gathering) 더미 데이터
export const gatheringData = [
  {
    id: 1,
    authorId: 1,
    category: "gathering",
    categoryLabel: "스터디",
    status: "모집중",
    title: "React 스터디 팀원 모집 (주 2회)",
    content:
      "<p>React 18의 새로운 기능들을 함께 공부할 스터디원을 모집합니다. 초급자도 환영!</p>",
    author: "김루이지",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "프론트엔드",
    time: "2시간 전",
    date: "2025-06-13 14:00",
    tags: ["React", "JavaScript", "초보환영", "백엔드"],
    likes: 5,
    comments: [],
    views: 123,
    image: null,
    contentList: null,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: 3,
    location: "경기도 화성 동탄",
    timeText: "화, 목 오후 7시",
    period: "2025.06.13 ~ 2025.07.13",
  },
  {
    id: 2,
    authorId: 2,
    category: "gathering",
    categoryLabel: "프로젝트",
    status: "모집완료",
    title: "사이드 프로젝트 팀원 구합니다",
    content: "<p>함께 성장할 사이드 프로젝트 팀원을 모집합니다.</p>",
    author: "홍길동",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "백엔드",
    time: "1일 전",
    date: "2025-06-12 10:00",
    tags: ["프로젝트", "협업"],
    likes: 2,
    comments: [],
    views: 45,
    image: null,
    contentList: null,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: 5,
    location: "서울 강남구",
    timeText: "주말 오전 10시",
    period: "2025.06.20 ~ 2025.08.20",
  },
];

// 커피챗/멘토링(match) 더미 데이터
export const matchData = [
  {
    id: 1,
    authorId: 9,
    category: "match",
    categoryLabel: "커피챗",
    status: "매칭가능",
    title: "프론트엔드 개발자 커피챗 구해요",
    content:
      "<p>프론트엔드 개발자와 진로, 취업 관련 커피챗 하실 분 구합니다.</p>",
    author: "이영희",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "프론트엔드",
    time: "2시간 전",
    date: "2025-06-13 15:00",
    tags: ["프론트엔드", "커피챗"],
    likes: 2,
    comments: [],
    views: 77,
    image: null,
    contentList: null,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: 1,
    location: "온라인",
    timeText: "협의 후 진행",
    period: "2025.06.13 ~ 2025.06.30",
  },
  {
    id: 2,
    authorId: 10,
    category: "match",
    categoryLabel: "멘토링",
    status: "매칭완료",
    title: "멘토링: 포트폴리오 첨삭해드립니다",
    content: "<p>포트폴리오 첨삭 및 피드백 멘토링 진행합니다.</p>",
    author: "박민수",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "멘토링",
    time: "3일 전",
    date: "2025-06-10 11:00",
    tags: ["멘토링", "포트폴리오"],
    likes: 1,
    comments: [],
    views: 55,
    image: null,
    contentList: null,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: 1,
    location: "온라인",
    timeText: "협의 후 진행",
    period: "2025.06.10 ~ 2025.06.30",
  },
];

// 장터(market) 더미 데이터
export const marketData = [
  {
    id: 1,
    authorId: 11,
    category: "market",
    categoryLabel: "중고거래",
    status: "판매중",
    title: "머쓱이 그립톡",
    price: 5000,
    images: [
      "/src/assets/masseuki.png",
      "https://attach.lolchess.gg/2023%2F10%2F11%2F1696972326935-1696972326935.png",
    ],
    content:
      "<p>머쓱이 얼굴이 그려진 귀여운 그립톡입니다. 미개봉 새상품!</p><p>측면 사진도 확인하세요.</p>",
    author: "최서적",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "서적판매",
    time: "4일 전",
    date: "2025-06-05 13:00",
    tags: ["서적", "중고"],
    likes: 0,
    comments: [],
    views: 34,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: null,
    location: "서울 강남구",
    timeText: null,
    period: null,
  },
  {
    id: 2,
    authorId: 12,
    category: "market",
    categoryLabel: "중고거래",
    status: "판매완료",
    title: "클린코드 책",
    price: 10000,
    images: [
      "https://via.placeholder.com/400x400.png?text=Clean+Code+Cover",
      "https://via.placeholder.com/400x400.png?text=Clean+Code+Page",
    ],
    content:
      "<p>클린코드 1권입니다. 상태 아주 좋습니다.</p><p>내부도 깨끗합니다.</p>",
    author: "박전자",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "전자제품",
    time: "5일 전",
    date: "2025-06-06 17:00",
    tags: ["모니터", "중고"],
    likes: 1,
    comments: [],
    views: 21,
    bookmarked: false,
    bookmarkCount: 0,
    recruitCount: null,
    location: "온라인 거래",
    timeText: null,
    period: null,
  },
  {
    id: 3,
    authorId: 1,
    category: "market",
    categoryLabel: "중고거래",
    status: "판매중",
    title: "이펙티브 자바 3/E",
    price: 15000,
    images: ["https://via.placeholder.com/400x400.png?text=Effective+Java"],
    content: "<p>이펙티브 자바 3판입니다. 거의 새 책입니다.</p>",
    author: "김루이지",
    authorProfileImg: "https://via.placeholder.com/40",
    devcourseName: "프론트엔드",
    time: "3일 전",
    date: "2025-06-11 18:00",
    tags: ["자바", "필독서"],
    likes: 12,
    comments: [],
    views: 180,
    bookmarked: true,
    bookmarkCount: 3,
    recruitCount: null,
    location: "경기도 수원시",
    timeText: null,
    period: null,
  },
];
