/**
 * 함께해요(스터디/프로젝트, 커피챗/멘토링) 게시판을 더미데이터
 * - boardType: 'gathering' (스터디/프로젝트), 'match' (커피챗/멘토링)
 */
export const togetherData = [
  // Gathering Posts (스터디/프로젝트)
  {
    postId: 1,
    boardType: "gathering",
    title: "React 스터디 팀원 모집 (주 2회)",
    content:
      "<p>React 18의 새로운 기능들을 함께 공부할 스터디원을 모집합니다. 초급자도 환영!</p>",
    viewCount: 123,
    likeCount: 5,
    isDeleted: false,
    createdAt: "2025-06-13T14:00:00Z",
    updatedAt: "2025-06-13T14:00:00Z",
    tags: ["React", "JavaScript", "초보환영"],
    user: {
      userId: 1,
      nickname: "김루이지",
      profileImg: "https://via.placeholder.com/40",
      devcourse: "프론트엔드",
    },
    gatheringType: "STUDY",
    status: "RECRUITING",
    headCount: 3,
    place: "경기도 화성 동탄",
    period: "3개월",
    requiredSkills: ["React", "TypeScript"],
    isLiked: false,
    isBookmarked: false,
    commentCount: 0,
  },
  {
    postId: 2,
    boardType: "gathering",
    title: "사이드 프로젝트 팀원 구합니다",
    content: "<p>함께 성장할 사이드 프로젝트 팀원을 모집합니다.</p>",
    viewCount: 45,
    likeCount: 2,
    isDeleted: false,
    createdAt: "2025-06-12T10:00:00Z",
    updatedAt: "2025-06-12T10:00:00Z",
    tags: ["프로젝트", "협업", "포트폴리오"],
    user: {
      userId: 2,
      nickname: "홍길동",
      profileImg: "https://via.placeholder.com/40",
      devcourse: "백엔드",
    },
    gatheringType: "PROJECT",
    status: "COMPLETED",
    headCount: 5,
    place: "서울 강남구",
    period: "2025.06.20 ~ 2025.08.20",
    requiredSkills: ["Spring Boot", "JPA", "React"],
    isLiked: true,
    isBookmarked: false,
    commentCount: 5,
  },
  // Match Posts (커피챗/멘토링)
  {
    postId: 3,
    boardType: "match",
    title: "프론트엔드 개발자 커피챗 구해요",
    content:
      "<p>프론트엔드 개발자와 진로, 취업 관련 커피챗 하실 분 구합니다.</p>",
    viewCount: 77,
    likeCount: 2,
    isDeleted: false,
    createdAt: "2025-06-13T15:00:00Z",
    updatedAt: "2025-06-13T15:00:00Z",
    tags: ["프론트엔드", "커피챗", "취업"],
    user: {
      userId: 9,
      nickname: "이영희",
      profileImg: "https://via.placeholder.com/40",
      devcourse: "프론트엔드",
    },
    matchType: "COFFEE_CHAT",
    status: "AVAILABLE",
    recruitmentType: "FRONTEND",
    isLiked: false,
    isBookmarked: true,
    commentCount: 2,
  },
  {
    postId: 4,
    boardType: "match",
    title: "멘토링: 포트폴리오 첨삭해드립니다",
    content: "<p>포트폴리오 첨삭 및 피드백 멘토링 진행합니다.</p>",
    viewCount: 55,
    likeCount: 1,
    isDeleted: false,
    createdAt: "2025-06-10T11:00:00Z",
    updatedAt: "2025-06-10T11:00:00Z",
    tags: ["멘토링", "포트폴리오", "백엔드"],
    user: {
      userId: 10,
      nickname: "박민수",
      profileImg: "https://via.placeholder.com/40",
      devcourse: "AI 엔지니어링",
    },
    matchType: "MENTORING",
    status: "COMPLETED",
    recruitmentType: "BACKEND",
    isLiked: false,
    isBookmarked: false,
    commentCount: 8,
  },
];
